package com.alvarotc.swissknife.ui.theme

import androidx.compose.ui.graphics.Color

// Brand primary — ecosystem brand-blue
val BrandBlue = Color(0xFF0070F3)
val BrandBlueDark = Color(0xFF3291FF)

// Dark theme
val DarkBackground = Color(0xFF09090B)
val DarkSurface = Color(0xFF111113)
val DarkSurfaceVariant = Color(0xFF1A1A1F)
val DarkSurfaceElevated = Color(0xFF222228)
val DarkOnBackground = Color(0xFFFAFAFA)
val DarkOnSurface = Color(0xFFE4E4E7)
val DarkOnSurfaceVariant = Color(0xFFA1A1AA)
val DarkOutline = Color(0xFF27272A)
val DarkOutlineVariant = Color(0xFF3F3F46)

val DarkPrimary = BrandBlueDark
val DarkOnPrimary = Color(0xFFFFFFFF)
val DarkPrimaryContainer = Color(0xFF0A2A5C)
val DarkOnPrimaryContainer = Color(0xFFBBDEFB)
val DarkError = Color(0xFFF87171)
val DarkOnError = Color(0xFF1A0000)

// Light theme
val LightBackground = Color(0xFFFAFAFA)
val LightSurface = Color(0xFFFFFFFF)
val LightSurfaceVariant = Color(0xFFF4F4F5)
val LightSurfaceElevated = Color(0xFFFFFFFF)
val LightOnBackground = Color(0xFF09090B)
val LightOnSurface = Color(0xFF18181B)
val LightOnSurfaceVariant = Color(0xFF71717A)
val LightOutline = Color(0xFFE4E4E7)
val LightOutlineVariant = Color(0xFFD4D4D8)

val LightPrimary = BrandBlue
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFDBEAFE)
val LightOnPrimaryContainer = Color(0xFF003A80)
val LightError = Color(0xFFDC2626)
val LightOnError = Color(0xFFFFFFFF)

// Tool accent colors — kept vibrant for both themes
val AccentCoin = Color(0xFFFBBF24)
val AccentDice = Color(0xFFF43F5E)
val AccentRandom = Color(0xFF22C55E)
val AccentSanta = Color(0xFF8B5CF6)
val AccentList = Color(0xFF38BDF8)
val AccentPassword = Color(0xFFFB923C)
val AccentWheel = Color(0xFFFACC15)
val AccentFinger = Color(0xFF3B82F6)
val AccentTimer = Color(0xFF14B8A6)
val AccentGroups = Color(0xFF6366F1)
val AccentRPS = Color(0xFFEF4444)
val AccentLottery = Color(0xFFD946EF)
val AccentEightBall = Color(0xFF06B6D4)
val AccentColor = Color(0xFFEC4899)
val AccentTeamName = Color(0xFF84CC16)

// Tool accent containers (dark theme)
val AccentCoinContainer = Color(0xFF422D08)
val AccentDiceContainer = Color(0xFF4C0D19)
val AccentRandomContainer = Color(0xFF0A3D1E)
val AccentSantaContainer = Color(0xFF2E1065)
val AccentListContainer = Color(0xFF0C2D48)
val AccentPasswordContainer = Color(0xFF431A08)
val AccentWheelContainer = Color(0xFF3D2E05)
val AccentFingerContainer = Color(0xFF172554)
val AccentTimerContainer = Color(0xFF042F2E)
val AccentGroupsContainer = Color(0xFF1E1B4B)
val AccentRPSContainer = Color(0xFF450A0A)
val AccentLotteryContainer = Color(0xFF4A044E)
val AccentEightBallContainer = Color(0xFF083344)
val AccentColorContainer = Color(0xFF500724)
val AccentTeamNameContainer = Color(0xFF1A2E05)

// Tool accent containers (light theme)
val AccentCoinContainerLight = Color(0xFFFEF3C7)
val AccentDiceContainerLight = Color(0xFFFFE4E6)
val AccentRandomContainerLight = Color(0xFFDCFCE7)
val AccentSantaContainerLight = Color(0xFFEDE9FE)
val AccentListContainerLight = Color(0xFFE0F2FE)
val AccentPasswordContainerLight = Color(0xFFFFEDD5)
val AccentWheelContainerLight = Color(0xFFFEF9C3)
val AccentFingerContainerLight = Color(0xFFDBEAFE)
val AccentTimerContainerLight = Color(0xFFCCFBF1)
val AccentGroupsContainerLight = Color(0xFFE0E7FF)
val AccentRPSContainerLight = Color(0xFFFEE2E2)
val AccentLotteryContainerLight = Color(0xFFFAE8FF)
val AccentEightBallContainerLight = Color(0xFFCFFAFE)
val AccentColorContainerLight = Color(0xFFFCE7F3)
val AccentTeamNameContainerLight = Color(0xFFECFCCB)
